import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]

[font]
size = 14

normal = { family = "ComicShannsMono Nerd Font", style = "Regular" }
bold = { family = "ComicShannsMono Nerd Font", style = "Bold" }
